---
- name: check if the subscription is valid
  shell: "subscription-manager status|grep 'Current'|wc -l"
  register: subs_valid
  changed_when: false

- name: Unregister Subs because subs is not valid
  redhat_subscription:
    username: "{{ subs.id }}"
    password: "{{ subs.pw }}"
    state: absent
  when: subs_valid.stdout != '1' and consumerid is not defined
#- debug: msg="{{subs.id}}"
#- debug: msg="{{subs.pw}}"
#- debug: msg="{{pool_id}}"
- name: Register node to rhsm and attach pool using id
  redhat_subscription:
    username: "{{ subs.id }}"
    password: "{{ subs.pw }}"
    pool_ids: "{{ pool_id }}"
    state: present
    force_register: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 1
  ignore_errors: yes
- debug: var=task_result

